// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>

import type { IHtmlBlock } from 'pumpkin-ts-models';

export const GENERATED_BLOCK_DEFAULT_CONTENT = {
  "Hero": {"type":"Main","headline":"","subheadline":"","backgroundImage":"","backgroundImageAltText":"","backgroundImagePosition":"center","mainImage":"","mainImageAltText":"","mainImageAspect":"auto","mainImageFit":"cover","mainImagePosition":"center","buttonText":"","buttonLink":""},
  "PrimaryCTA": {"title":"","description":"","buttonText":"","buttonLink":"","secondaryText":"","secondaryLinkText":"","secondaryLink":"","backgroundImage":"","backgroundImagePosition":"center","mainImage":"","mainImageAspect":"auto","mainImageFit":"cover","mainImagePosition":"center","alt":""},
  "SecondaryCTA": {"title":"","description":"","buttonText":"","buttonLink":""},
  "CardGrid": {"title":"","subtitle":"","layout":"grid-3","imageAspect":"auto","imageFit":"cover","imagePosition":"center","cards":[]},
  "FAQ": {"title":"","subtitle":"","layout":"accordion","items":[]},
  "HubSpokes": {"title":"Related pages","subtitle":"","hubPageSlug":"","layout":"cards","limit":12,"showExcerpt":true,"showLocation":true,"ctaText":"Learn more","spokes":[]},
  "Breadcrumbs": {"items":[]},
  "TrustBar": {"items":[]},
  "HowItWorks": {"title":"","steps":[]},
  "ServiceAreaMap": {"title":"","subtitle":"","mapEmbedUrl":"","neighborhoods":[],"zipCodes":[],"nearbyCities":[]},
  "LocalProTips": {"title":"","items":[]},
  "Gallery": {"title":"","subtitle":"","imageAspect":"auto","imageFit":"cover","imagePosition":"center","images":[]},
  "Testimonials": {"title":"","subtitle":"","layout":"carousel","items":[]},
  "Contact": {"id":"","title":"","subtitle":"","address":"","phone":"","email":"","hours":"","formFields":[],"submitButtonText":"Submit","socialLinks":[]},
  "Form": {"formType":"contact","title":"","subtitle":"","description":"","layout":"default","successMessage":""},
  "Blog": {"title":"","subtitle":"","author":"","authorImage":"","authorBio":"","publishedDate":"","featuredImage":"","featuredImageAlt":"","featuredImageAspect":"auto","featuredImageFit":"cover","featuredImagePosition":"center","excerpt":"","body":"","tags":[],"categories":[],"readingTime":0,"relatedImageAspect":"auto","relatedImageFit":"cover","relatedImagePosition":"center","relatedPosts":[]},
} as const;

export function createGeneratedDefaultBlock(type: string): IHtmlBlock {
  const content = GENERATED_BLOCK_DEFAULT_CONTENT[type as keyof typeof GENERATED_BLOCK_DEFAULT_CONTENT] ?? {};
  return { type, schemaVersion: 1, content: structuredClone(content) } as IHtmlBlock;
}
