export const formDefaults = {
  root: 'w-full py-12',
  container: 'max-w-3xl mx-auto px-6',
  header: 'mb-8 text-center',
  title: 'text-3xl font-bold text-neutral-900',
  subtitle: 'mt-3 text-base text-neutral-600',
  description: 'mt-3 text-sm text-neutral-500',
  form: 'grid grid-cols-1 gap-4',
  fieldWrapper: '',
  fieldWrapperHalf: '',
  fieldWrapperThird: '',
  fieldWrapperTwoThirds: '',
  fieldLabel: 'block text-sm font-medium text-neutral-700 mb-1',
  requiredMarker: 'text-red-500',
  fieldHelp: 'mt-1 text-xs text-neutral-500',
  fieldInput: 'w-full px-3 py-2 text-sm border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-orange-400',
  fieldTextarea: 'w-full px-3 py-2 text-sm border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-orange-400 min-h-[120px]',
  fieldSelect: 'w-full px-3 py-2 text-sm border border-neutral-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-orange-400 focus:border-orange-400',
  choiceGroup: 'space-y-2',
  choiceLabel: 'flex items-center gap-2 text-sm text-neutral-700',
  checkboxLabel: 'flex items-start gap-2 text-sm text-neutral-700',
  submitButton: 'w-full px-6 py-2.5 bg-orange-500 text-white font-semibold rounded-lg hover:bg-orange-600 transition-colors',
  statusMessage: 'rounded-lg px-4 py-3 text-sm',
  successMessage: 'bg-green-50 text-green-700',
  errorMessage: 'bg-red-50 text-red-700',
  emptyState: 'text-sm text-neutral-500',
};

export type FormClassNames = Partial<typeof formDefaults>;
