export const headerDefaults = {
  root: 'w-full border-b border-neutral-200 bg-white',
  container: 'max-w-6xl mx-auto px-6 flex items-center justify-between h-16',
  logoWrapper: 'flex items-center gap-2',
  logoIcon: 'text-2xl',
  logoImage: 'h-8 w-auto',
  logoText: 'text-lg font-bold text-neutral-900',
  nav: 'hidden md:flex items-center gap-6 text-sm font-medium text-neutral-600',
  navLink: 'hover:text-orange-600 transition-colors',
  navLinkActive: 'text-orange-600 font-semibold',
  navDropdown: 'relative',
  navDropdownTrigger: 'inline-flex items-center gap-1 hover:text-orange-600 transition-colors',
  navDropdownArrow: 'w-3.5 h-3.5 transition-transform',
  navDropdownArrowOpen: 'w-3.5 h-3.5 transition-transform rotate-180',
  navDropdownMenu: 'absolute top-full left-0 mt-2 bg-white border border-neutral-200 rounded-lg shadow-lg py-1.5 min-w-[180px] z-50',
  navDropdownItem: 'block px-4 py-2 text-sm text-neutral-600 hover:text-orange-600 hover:bg-neutral-50 transition-colors',
  ctaButton: 'hidden md:inline-flex items-center px-5 py-2 bg-orange-500 text-white text-sm font-bold rounded-lg hover:bg-orange-600 transition-all',
  mobileToggle: 'md:hidden p-2 text-neutral-600 hover:text-neutral-900',
  mobileMenu: 'md:hidden border-t border-neutral-200 bg-white px-6 py-4 space-y-1',
  mobileLink: 'block py-2 text-sm text-neutral-600 hover:text-orange-600 transition-colors',
  mobileDropdownTrigger: 'flex items-center justify-between w-full py-2 text-sm text-neutral-600 hover:text-orange-600 transition-colors',
  mobileDropdownArrow: 'w-4 h-4 transition-transform',
  mobileDropdownArrowOpen: 'w-4 h-4 transition-transform rotate-180',
  mobileSubMenu: 'pl-4 space-y-1 pb-1',
  mobileSubLink: 'block py-1.5 text-sm text-neutral-500 hover:text-orange-600 transition-colors',
  mobileCta: 'block w-full text-center mt-3 px-5 py-2 bg-orange-500 text-white text-sm font-bold rounded-lg hover:bg-orange-600 transition-all',
};

export type HeaderClassNames = Partial<typeof headerDefaults>;
