// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>
#nullable enable
using System.Text.Json;
using System.Text.Json.Serialization;

namespace pumpkin_net_models.Models;

public class HeroBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Hero";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new HeroContent();
}

public class HeroContent
{
    [JsonPropertyName("type")]
    public string Type { get; set; } = "Main";

    [JsonPropertyName("headline")]
    public string Headline { get; set; } = string.Empty;

    [JsonPropertyName("subheadline")]
    public string Subheadline { get; set; } = string.Empty;

    [JsonPropertyName("backgroundImage")]
    public string BackgroundImage { get; set; } = string.Empty;

    [JsonPropertyName("backgroundImageAltText")]
    public string BackgroundImageAltText { get; set; } = string.Empty;

    [JsonPropertyName("backgroundImagePosition")]
    public string? BackgroundImagePosition { get; set; } = "center";

    [JsonPropertyName("mainImage")]
    public string MainImage { get; set; } = string.Empty;

    [JsonPropertyName("mainImageAltText")]
    public string MainImageAltText { get; set; } = string.Empty;

    [JsonPropertyName("mainImageAspect")]
    public string? MainImageAspect { get; set; } = "auto";

    [JsonPropertyName("mainImageFit")]
    public string? MainImageFit { get; set; } = "cover";

    [JsonPropertyName("mainImagePosition")]
    public string? MainImagePosition { get; set; } = "center";

    [JsonPropertyName("buttonText")]
    public string ButtonText { get; set; } = string.Empty;

    [JsonPropertyName("buttonLink")]
    public string ButtonLink { get; set; } = string.Empty;
}

public class PrimaryCtaBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "PrimaryCTA";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new PrimaryCtaContent();
}

public class PrimaryCtaContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("buttonText")]
    public string ButtonText { get; set; } = string.Empty;

    [JsonPropertyName("buttonLink")]
    public string ButtonLink { get; set; } = string.Empty;

    [JsonPropertyName("secondaryText")]
    public string SecondaryText { get; set; } = string.Empty;

    [JsonPropertyName("secondaryLinkText")]
    public string SecondaryLinkText { get; set; } = string.Empty;

    [JsonPropertyName("secondaryLink")]
    public string SecondaryLink { get; set; } = string.Empty;

    [JsonPropertyName("backgroundImage")]
    public string BackgroundImage { get; set; } = string.Empty;

    [JsonPropertyName("backgroundImagePosition")]
    public string? BackgroundImagePosition { get; set; } = "center";

    [JsonPropertyName("mainImage")]
    public string MainImage { get; set; } = string.Empty;

    [JsonPropertyName("mainImageAspect")]
    public string? MainImageAspect { get; set; } = "auto";

    [JsonPropertyName("mainImageFit")]
    public string? MainImageFit { get; set; } = "cover";

    [JsonPropertyName("mainImagePosition")]
    public string? MainImagePosition { get; set; } = "center";

    [JsonPropertyName("alt")]
    public string Alt { get; set; } = string.Empty;
}

public class SecondaryCtaBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "SecondaryCTA";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new SecondaryCtaContent();
}

public class SecondaryCtaContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("buttonText")]
    public string ButtonText { get; set; } = string.Empty;

    [JsonPropertyName("buttonLink")]
    public string ButtonLink { get; set; } = string.Empty;
}

public class CardGridBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "CardGrid";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new CardGridContent();
}

public class Card
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("image-alt")]
    public string ImageAltLegacy { get; set; } = string.Empty;

    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    [JsonPropertyName("link")]
    public string Link { get; set; } = string.Empty;

    [JsonPropertyName("alt")]
    public string Alt { get; set; } = string.Empty;
}

public class CardGridContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("layout")]
    public string Layout { get; set; } = "grid-3";

    [JsonPropertyName("imageAspect")]
    public string? ImageAspect { get; set; } = "auto";

    [JsonPropertyName("imageFit")]
    public string? ImageFit { get; set; } = "cover";

    [JsonPropertyName("imagePosition")]
    public string? ImagePosition { get; set; } = "center";

    [JsonPropertyName("cards")]
    public List<Card> Cards { get; set; } = new();
}

public class FaqBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "FAQ";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new FaqContent();
}

public class FaqItem
{
    [JsonPropertyName("question")]
    public string Question { get; set; } = string.Empty;

    [JsonPropertyName("answer")]
    public string Answer { get; set; } = string.Empty;
}

public class FaqContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("layout")]
    public string Layout { get; set; } = "accordion";

    [JsonPropertyName("items")]
    public List<FaqItem> Items { get; set; } = new();
}

public class HubSpokesBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "HubSpokes";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new HubSpokesContent();
}

public class HubSpokeLink
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string Description { get; set; } = string.Empty;

    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    [JsonPropertyName("city")]
    public string City { get; set; } = string.Empty;

    [JsonPropertyName("state")]
    public string State { get; set; } = string.Empty;

    [JsonPropertyName("metro")]
    public string Metro { get; set; } = string.Empty;

    [JsonPropertyName("spokePriority")]
    public int SpokePriority { get; set; } = 0;
}

public class HubSpokesContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = "Related pages";

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("hubPageSlug")]
    public string HubPageSlug { get; set; } = string.Empty;

    [JsonPropertyName("layout")]
    public string Layout { get; set; } = "cards";

    [JsonPropertyName("limit")]
    public int Limit { get; set; } = 12;

    [JsonPropertyName("showExcerpt")]
    public bool ShowExcerpt { get; set; } = true;

    [JsonPropertyName("showLocation")]
    public bool ShowLocation { get; set; } = true;

    [JsonPropertyName("ctaText")]
    public string CtaText { get; set; } = "Learn more";

    [JsonPropertyName("spokes")]
    public List<HubSpokeLink> Spokes { get; set; } = new();
}

public class BreadcrumbsBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Breadcrumbs";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new BreadcrumbsContent();
}

public class BreadcrumbItem
{
    [JsonPropertyName("label")]
    public string Label { get; set; } = string.Empty;

    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    [JsonPropertyName("current")]
    public bool Current { get; set; } = false;
}

public class BreadcrumbsContent
{
    [JsonPropertyName("items")]
    public List<BreadcrumbItem> Items { get; set; } = new();
}

public class TrustBarBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "TrustBar";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new TrustBarContent();
}

public class TrustBarItem
{
    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;

    [JsonPropertyName("alt")]
    public string Alt { get; set; } = string.Empty;
}

public class TrustBarContent
{
    [JsonPropertyName("items")]
    public List<TrustBarItem> Items { get; set; } = new();
}

public class HowItWorksBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "HowItWorks";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new HowItWorksContent();
}

public class Step
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;

    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("alt")]
    public string Alt { get; set; } = string.Empty;
}

public class HowItWorksContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("steps")]
    public List<Step> Steps { get; set; } = new();
}

public class ServiceAreaMapBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "ServiceAreaMap";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new ServiceAreaMapContent();
}

public class ServiceAreaMapContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("mapEmbedUrl")]
    public string MapEmbedUrl { get; set; } = string.Empty;

    [JsonPropertyName("neighborhoods")]
    public List<string> Neighborhoods { get; set; } = new();

    [JsonPropertyName("zipCodes")]
    public List<string> ZipCodes { get; set; } = new();

    [JsonPropertyName("nearbyCities")]
    public List<string> NearbyCities { get; set; } = new();
}

public class LocalProTipsBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "LocalProTips";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new LocalProTipsContent();
}

public class ProTipItem
{
    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;

    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;
}

public class LocalProTipsContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("items")]
    public List<ProTipItem> Items { get; set; } = new();
}

public class GalleryBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Gallery";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new GalleryContent();
}

public class GalleryImage
{
    [JsonPropertyName("src")]
    public string Src { get; set; } = string.Empty;

    [JsonPropertyName("alt")]
    public string Alt { get; set; } = string.Empty;

    [JsonPropertyName("caption")]
    public string Caption { get; set; } = string.Empty;
}

public class GalleryContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("imageAspect")]
    public string? ImageAspect { get; set; } = "auto";

    [JsonPropertyName("imageFit")]
    public string? ImageFit { get; set; } = "cover";

    [JsonPropertyName("imagePosition")]
    public string? ImagePosition { get; set; } = "center";

    [JsonPropertyName("images")]
    public List<GalleryImage> Images { get; set; } = new();
}

public class TestimonialsBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Testimonials";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new TestimonialsContent();
}

public class TestimonialItem
{
    [JsonPropertyName("quote")]
    public string Quote { get; set; } = string.Empty;

    [JsonPropertyName("author")]
    public string Author { get; set; } = string.Empty;

    [JsonPropertyName("eventType")]
    public string EventType { get; set; } = string.Empty;

    [JsonPropertyName("rating")]
    public int Rating { get; set; } = 5;
}

public class TestimonialsContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("layout")]
    public string Layout { get; set; } = "carousel";

    [JsonPropertyName("items")]
    public List<TestimonialItem> Items { get; set; } = new();
}

public class ContactBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Contact";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new ContactContent();
}

public class FormField
{
    [JsonPropertyName("label")]
    public string Label { get; set; } = string.Empty;

    [JsonPropertyName("type")]
    public string Type { get; set; } = "text";

    [JsonPropertyName("required")]
    public bool Required { get; set; } = false;

    [JsonPropertyName("placeholder")]
    public string Placeholder { get; set; } = string.Empty;
}

public class SocialLink
{
    [JsonPropertyName("platform")]
    public string Platform { get; set; } = string.Empty;

    [JsonPropertyName("url")]
    public string Url { get; set; } = string.Empty;

    [JsonPropertyName("icon")]
    public string Icon { get; set; } = string.Empty;
}

public class ContactContent
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = string.Empty;

    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("address")]
    public string Address { get; set; } = string.Empty;

    [JsonPropertyName("phone")]
    public string Phone { get; set; } = string.Empty;

    [JsonPropertyName("email")]
    public string Email { get; set; } = string.Empty;

    [JsonPropertyName("hours")]
    public string Hours { get; set; } = string.Empty;

    [JsonPropertyName("formFields")]
    public List<FormField> FormFields { get; set; } = new();

    [JsonPropertyName("submitButtonText")]
    public string SubmitButtonText { get; set; } = "Submit";

    [JsonPropertyName("socialLinks")]
    public List<SocialLink> SocialLinks { get; set; } = new();
}

public class FormBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Form";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new FormBlockContent();
}

public class FormBlockContent
{
    [JsonPropertyName("formType")]
    public string FormType { get; set; } = "contact";

    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("description")]
    public string? Description { get; set; } = string.Empty;

    [JsonPropertyName("layout")]
    public string Layout { get; set; } = "default";

    [JsonPropertyName("successMessage")]
    public string SuccessMessage { get; set; } = string.Empty;
}

public class BlogBlock : HtmlBlockBase
{
    [JsonPropertyName("type")]
    public override string Type { get; set; } = "Blog";

    [JsonPropertyName("content")]
    public override object Content { get; set; } = new BlogContent();
}

public class RelatedPost
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("slug")]
    public string Slug { get; set; } = string.Empty;

    [JsonPropertyName("excerpt")]
    public string Excerpt { get; set; } = string.Empty;

    [JsonPropertyName("image")]
    public string Image { get; set; } = string.Empty;

    [JsonPropertyName("imageAlt")]
    public string ImageAlt { get; set; } = string.Empty;

    [JsonPropertyName("publishedDate")]
    public string PublishedDate { get; set; } = string.Empty;
}

public class BlogContent
{
    [JsonPropertyName("title")]
    public string Title { get; set; } = string.Empty;

    [JsonPropertyName("subtitle")]
    public string Subtitle { get; set; } = string.Empty;

    [JsonPropertyName("author")]
    public string Author { get; set; } = string.Empty;

    [JsonPropertyName("authorImage")]
    public string AuthorImage { get; set; } = string.Empty;

    [JsonPropertyName("authorBio")]
    public string AuthorBio { get; set; } = string.Empty;

    [JsonPropertyName("publishedDate")]
    public string PublishedDate { get; set; } = string.Empty;

    [JsonPropertyName("featuredImage")]
    public string FeaturedImage { get; set; } = string.Empty;

    [JsonPropertyName("featuredImageAlt")]
    public string FeaturedImageAlt { get; set; } = string.Empty;

    [JsonPropertyName("featuredImageAspect")]
    public string? FeaturedImageAspect { get; set; } = "auto";

    [JsonPropertyName("featuredImageFit")]
    public string? FeaturedImageFit { get; set; } = "cover";

    [JsonPropertyName("featuredImagePosition")]
    public string? FeaturedImagePosition { get; set; } = "center";

    [JsonPropertyName("excerpt")]
    public string Excerpt { get; set; } = string.Empty;

    [JsonPropertyName("body")]
    public string Body { get; set; } = string.Empty;

    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; } = new();

    [JsonPropertyName("categories")]
    public List<string> Categories { get; set; } = new();

    [JsonPropertyName("readingTime")]
    public int ReadingTime { get; set; } = 0;

    [JsonPropertyName("relatedImageAspect")]
    public string? RelatedImageAspect { get; set; } = "auto";

    [JsonPropertyName("relatedImageFit")]
    public string? RelatedImageFit { get; set; } = "cover";

    [JsonPropertyName("relatedImagePosition")]
    public string? RelatedImagePosition { get; set; } = "center";

    [JsonPropertyName("relatedPosts")]
    public List<RelatedPost> RelatedPosts { get; set; } = new();
}

internal static class GeneratedBlockTypeRegistry
{
    internal static readonly IReadOnlyDictionary<string, Type> Types = new Dictionary<string, Type>(StringComparer.Ordinal)
    {
        ["Hero"] = typeof(HeroBlock),
        ["PrimaryCTA"] = typeof(PrimaryCtaBlock),
        ["SecondaryCTA"] = typeof(SecondaryCtaBlock),
        ["CardGrid"] = typeof(CardGridBlock),
        ["FAQ"] = typeof(FaqBlock),
        ["HubSpokes"] = typeof(HubSpokesBlock),
        ["Breadcrumbs"] = typeof(BreadcrumbsBlock),
        ["TrustBar"] = typeof(TrustBarBlock),
        ["HowItWorks"] = typeof(HowItWorksBlock),
        ["ServiceAreaMap"] = typeof(ServiceAreaMapBlock),
        ["LocalProTips"] = typeof(LocalProTipsBlock),
        ["Gallery"] = typeof(GalleryBlock),
        ["Testimonials"] = typeof(TestimonialsBlock),
        ["Contact"] = typeof(ContactBlock),
        ["Form"] = typeof(FormBlock),
        ["Blog"] = typeof(BlogBlock),
    };
}

public static class HtmlBlockContractValidator
{
    private static readonly IReadOnlyDictionary<string, string[]> RequiredContentProperties =
        new Dictionary<string, string[]>(StringComparer.Ordinal)
        {
            ["Hero"] = new[] { "type", "headline", "subheadline", "backgroundImage", "backgroundImageAltText", "mainImage", "mainImageAltText", "buttonText", "buttonLink" },
            ["PrimaryCTA"] = new[] { "title", "description", "buttonText", "buttonLink", "secondaryText", "secondaryLinkText", "secondaryLink", "backgroundImage", "mainImage", "alt" },
            ["SecondaryCTA"] = new[] { "title", "description", "buttonText", "buttonLink" },
            ["CardGrid"] = new[] { "title", "subtitle", "layout", "cards" },
            ["FAQ"] = new[] { "title", "subtitle", "layout", "items" },
            ["HubSpokes"] = new[] { "title", "subtitle", "hubPageSlug", "layout", "limit", "showExcerpt", "showLocation", "ctaText", "spokes" },
            ["Breadcrumbs"] = new[] { "items" },
            ["TrustBar"] = new[] { "items" },
            ["HowItWorks"] = new[] { "title", "steps" },
            ["ServiceAreaMap"] = new[] { "title", "subtitle", "mapEmbedUrl", "neighborhoods", "zipCodes", "nearbyCities" },
            ["LocalProTips"] = new[] { "title", "items" },
            ["Gallery"] = new[] { "title", "subtitle", "images" },
            ["Testimonials"] = new[] { "title", "subtitle", "layout", "items" },
            ["Contact"] = new[] { "id", "title", "subtitle", "address", "phone", "email", "hours", "formFields", "submitButtonText", "socialLinks" },
            ["Form"] = new[] { "formType", "title", "subtitle", "layout", "successMessage" },
            ["Blog"] = new[] { "title", "subtitle", "author", "authorImage", "authorBio", "publishedDate", "featuredImage", "featuredImageAlt", "excerpt", "body", "tags", "categories", "readingTime", "relatedPosts" },
        };

    public static IReadOnlyList<string> ValidatePage(Page page)
    {
        var errors = new List<string>();
        for (var index = 0; index < page.ContentData.ContentBlocks.Count; index++)
        {
            var block = page.ContentData.ContentBlocks[index];
            if (!RequiredContentProperties.TryGetValue(block.Type, out var required)) continue;

            if (block.Content is null)
            {
                errors.Add($"ContentData.ContentBlocks[{index}].content must be an object.");
                continue;
            }

            var content = block.Content is JsonElement element
                ? element
                : JsonSerializer.SerializeToElement(block.Content, block.Content.GetType());
            if (content.ValueKind != JsonValueKind.Object)
            {
                errors.Add($"ContentData.ContentBlocks[{index}].content must be an object.");
                continue;
            }

            foreach (var property in required)
            {
                if (!content.TryGetProperty(property, out _))
                    errors.Add($"ContentData.ContentBlocks[{index}].content.{property} is required for {block.Type}.");
            }
        }
        return errors;
    }
}
