// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>

import type { IHtmlBlock } from './IHtmlBlock';

export type MenuPricingLayout = "sections" | "cards" | "compact";

export interface MenuPricingItem {
  name: string;
  description: string;
  price: string;
  badge: string;
  image: string;
  imageAlt: string;
}

export interface MenuPricingSection {
  title: string;
  description: string;
  items: MenuPricingItem[];
}

export interface MenuPricingContent {
  title: string;
  subtitle: string;
  layout: MenuPricingLayout;
  currency: string;
  showPrices: boolean;
  sections: MenuPricingSection[];
}

export interface MenuPricingBlock extends IHtmlBlock {
  type: "MenuPricing";
  content: MenuPricingContent;
}

export type EventPackagesLayout = "grid" | "featured" | "compact";

export interface EventPackageItem {
  name: string;
  description: string;
  price: string;
  priceNote: string;
  image: string;
  imageAlt: string;
  features: string[];
  ctaText: string;
  ctaLink: string;
  highlighted: boolean;
}

export interface EventPackagesContent {
  title: string;
  subtitle: string;
  layout: EventPackagesLayout;
  packages: EventPackageItem[];
}

export interface EventPackagesBlock extends IHtmlBlock {
  type: "EventPackages";
  content: EventPackagesContent;
}
