// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>

import type { IHtmlBlock } from './IHtmlBlock';

import type { ImageAspect, ImageFit, ImagePosition } from './ImagePresentation';

export interface PrimaryCtaContent {
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
  secondaryText: string;
  secondaryLinkText: string;
  secondaryLink: string;
  backgroundImage: string;
  backgroundImagePosition?: ImagePosition;
  mainImage: string;
  mainImageAspect?: ImageAspect;
  mainImageFit?: ImageFit;
  mainImagePosition?: ImagePosition;
  alt: string;
}

export interface PrimaryCtaBlock extends IHtmlBlock {
  type: "PrimaryCTA";
  content: PrimaryCtaContent;
}

export interface SecondaryCtaContent {
  title: string;
  description: string;
  buttonText: string;
  buttonLink: string;
}

export interface SecondaryCtaBlock extends IHtmlBlock {
  type: "SecondaryCTA";
  content: SecondaryCtaContent;
}
