// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>

import type { IHtmlBlock } from './IHtmlBlock';
import type { HeroBlock } from './HeroBlocks';
import type { PrimaryCtaBlock } from './CtaBlocks';
import type { SecondaryCtaBlock } from './CtaBlocks';
import type { CardGridBlock } from './ContentBlocks';
import type { FaqBlock } from './ContentBlocks';
import type { HubSpokesBlock } from './ContentBlocks';
import type { BreadcrumbsBlock } from './NavigationBlocks';
import type { TrustBarBlock } from './NavigationBlocks';
import type { HowItWorksBlock } from './NavigationBlocks';
import type { ServiceAreaMapBlock } from './NavigationBlocks';
import type { LocalProTipsBlock } from './NavigationBlocks';
import type { GalleryBlock } from './InteractionBlocks';
import type { TestimonialsBlock } from './InteractionBlocks';
import type { ContactBlock } from './InteractionBlocks';
import type { FormBlock } from './InteractionBlocks';
import type { BlogBlock } from './BlogBlocks';

export type HtmlBlock =
   HeroBlock
  | PrimaryCtaBlock
  | SecondaryCtaBlock
  | CardGridBlock
  | FaqBlock
  | HubSpokesBlock
  | BreadcrumbsBlock
  | TrustBarBlock
  | HowItWorksBlock
  | ServiceAreaMapBlock
  | LocalProTipsBlock
  | GalleryBlock
  | TestimonialsBlock
  | ContactBlock
  | FormBlock
  | BlogBlock
;

export const BLOCK_TYPE_MAP = {
  "Hero": "HeroBlock",
  "PrimaryCTA": "PrimaryCtaBlock",
  "SecondaryCTA": "SecondaryCtaBlock",
  "CardGrid": "CardGridBlock",
  "FAQ": "FaqBlock",
  "HubSpokes": "HubSpokesBlock",
  "Breadcrumbs": "BreadcrumbsBlock",
  "TrustBar": "TrustBarBlock",
  "HowItWorks": "HowItWorksBlock",
  "ServiceAreaMap": "ServiceAreaMapBlock",
  "LocalProTips": "LocalProTipsBlock",
  "Gallery": "GalleryBlock",
  "Testimonials": "TestimonialsBlock",
  "Contact": "ContactBlock",
  "Form": "FormBlock",
  "Blog": "BlogBlock",
} as const;

export const SUPPORTED_BLOCK_TYPES = Object.keys(BLOCK_TYPE_MAP) as Array<keyof typeof BLOCK_TYPE_MAP>;

export function isBlockOfType<T extends HtmlBlock['type']>(
  block: IHtmlBlock,
  type: T,
): block is Extract<HtmlBlock, { type: T }> {
  return block.type === type;
}

export function isHtmlBlock(obj: unknown): obj is IHtmlBlock {
  if (!obj || typeof obj !== 'object') return false;
  const candidate = obj as { type?: unknown; content?: unknown };
  return typeof candidate.type === 'string' && !!candidate.content && typeof candidate.content === 'object';
}

export function createGenericBlock(type: string, content: Record<string, unknown>): IHtmlBlock {
  return { type, content };
}
