// <auto-generated> Generated from schemas/blocks. Do not edit by hand. </auto-generated>

import type { IHtmlBlock } from './IHtmlBlock';

import type { ImageAspect } from './ImagePresentation';

export type VideoProvider = "YouTube" | "Vimeo" | "External";

export interface VideoContent {
  title: string;
  subtitle: string;
  provider: VideoProvider;
  url: string;
  caption: string;
  aspect: ImageAspect;
  autoplay: boolean;
  muted: boolean;
}

export interface VideoBlock extends IHtmlBlock {
  type: "Video";
  content: VideoContent;
}
